[workspace]
members = [
  "services/telegram-bot",
  "services/solana-service",
  "services/api-gateway",
  #"services/trading-engine",
  #"services/analytics-service",
  "shared/proto-gen",
  #"shared/config",
  #"shared/utils",
  #"shared/database"
]
